---
test_name: Create a user
stages:
- name: Create a new user
  request:
    url: http://localhost:5000/users
    json:
      username: user10@gmail.com
      password: qwe
      display_name: User3
    method: POST
    headers:
      content-type: application/json
  response:
    status_code: 201
---

---
test_name: Post an article
stages:
- name: Post an article
  request:
    url: http://localhost:5001/articles
    method: POST
    auth:
    - user10@gmail.com
    - qwe
    json:
      text: This is my 1st article
      author: ABC
      title: 1st article
      url: abc.com
    headers:
      content-type: application/json
  response:
    status_code: 201
---

---
test_name: Try to add a comment to an article that doesn’t exist
stages:
- name: Try to add a comment to an article that doesn’t exist
  request:
    url: http://localhost:5002/comments
    json:
      user_id: 1
      author: user123
      title: title1
      display_name: user1
      comment: This is a Comment
    method: POST
    auth:
    - user10@gmail.com
    - qwe
    headers:
      content-type: application/json
  response:
    status_code: 404
---

---
test_name: Post an anonymous comment on an article
stages:
- name: Post an anonymous comment on an article
  request:
    url: http://localhost:5002/comments
    json:
      author: ABC
      title: 1st article
      comment: This is a Comment
    method: POST
    headers:
      content-type: application/json
  response:
    status_code: 201
---

---
test_name: Post an authenticated comment on an article
stages:
- name: Post an authenticated comment on an article
  request:
    url: http://localhost:5002/comments
    json:
      user_id: 1
      author: QWE
      title: ABC
      display_name: user1
      comment: This is a Comment
    method: POST
    auth:
    - user10@gmail.com
    - qwe
    headers:
      content-type: application/json
  response:
    status_code: 201
---