---
test_name: Create a user
stages:
- name: Create a new user
  request:
    url: http://localhost/user
    json:
      username: user30@gmail.com
      password: qwe
      display_name: user30
    method: POST
    headers:
      content-type: application/json
  response:
    status_code: 201
---

---
test_name: Post an article
stages:
- name: Post an article
  request:
    url: http://localhost/article
    method: POST
    auth:
    - user30@gmail.com
    - qwe
    json:
      text: This is my 1st article
      author: AB
      title: 1st article
      url: abc.com
    headers:
      content-type: application/json
  response:
    status_code: 201
#---

---
test_name: Try to add a comment to an article that doesn’t exist
stages:
- name: Try to add a comment to an article that doesn’t exist
  request:
    url: http://localhost/comment
    json:
      article_name: 3rd article
      comment: This is a comment
    method: POST
    auth:
    - user30@gmail.com
    - qwe
    headers:
      content-type: application/json
  response:
    status_code: 404
---

---
test_name: Post an authenticated comment on an article
stages:
- name: Post an authenticated comment on an article
  request:
    url: http://localhost/comment
    json:
      article_name: 1st article
      comment: The article is motivative
    method: POST
    auth:
    - user30@gmail.com
    - qwe
    headers:
      content-type: application/json
  response:
    status_code: 201
---